# Docker Compose file for CPU version
name: mt-photos-ai-cpu

services:
  mt-photos-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt-photos-ai-cpu
    ports:
      - "3004:3004"
    volumes:
      - ./model-cache:/model-cache
      - ./model-cache/paddleocr:/model-cache/paddleocr
    environment:
      - API_AUTH_KEY=mt_photos_ai_extra
      - CLIP_MODEL_NAME=nllb-clip-large-siglip__v1
      - FACE_MODEL_NAME=antelopev2
      - DEVICE=cpu
      - FACE_THRESHOLD=0.7
      - LOG_LEVEL=INFO
      - PYTHONHTTPSVERIFY=0
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
